/**
 * Created by rroman681 on 6/20/17.
 * Constants for Redux
 */
const constants = {
    // In the beginning
    SET_DIFFICULTY: "SET_DIFFICULTY",
    FETCH_CHARACTERS: "FETCH_CHARACTERS",
    SET_CHARACTERS: "SET_CHARACTERS",
    CANCEL_FETCHING: "CANCEL_FETCHING",

    // Counting
    INCREMENT_CORRECT: "INCREMENT_CORRECT",
    INCREMENT_TOTAL: "INCREMENT_TOTAL",
    RESET_ALL: "RESET_ALL",

    // Clicking the cards
    PUSH_GUESS: "PUSH_GUESS",
    EMPTY_GUESS: "EMPTY_GUESS",
    RETIRE_CHAR: "RETIRE_CHAR",
    RETIRE_CARD: "RETIRE_CARD",
    CREATE_RETIRE: "CREATE_RETIRE",
    RESET_RETIRE: "RESET_RETIRE",
    CREATE_ACTIVE: "CREATE_ACTIVE",
    ACTIVATE_CARD: "ACTIVATE_CARD",
    DEACTIVATE_CARD: "DEACTIVATE_CARD",

    // Game is finished
    FINISH_GAME: "FINISH_GAME",
    RESET_GAME: "RESET_GAME",

    // Error handling
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
};

export default constants